############################
# Camunda BPM
############################
camunda.bpm:
  webapp:
    index-redirect-enabled: false
  admin-user:
    id: admin
    password: admin

############################
# Spring
############################
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false

############################
# Spring Security
############################
security:
  basic:
    enabled: false
    
############################
# Tomcat
############################
server:
    port: 9090